# Generated by Django 4.2.7 on 2025-04-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0001_initial')]

    operations = [
        migrations.AddField(model_name='admission', name='city', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='admission', name='district', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='admission', name='pin_code', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='admission', name='state', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='admission', name='whatsapp_number', field=models.CharField(max_length=30, null=True)),
        migrations.AddField(model_name='historicaladmission', name='city', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='historicaladmission', name='district', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='historicaladmission', name='pin_code', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='historicaladmission', name='state', field=models.CharField(blank=True, max_length=180, null=True)),
        migrations.AddField(model_name='historicaladmission', name='whatsapp_number', field=models.CharField(max_length=30, null=True)),
    ]
