# Generated by Django 4.2.7 on 2025-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0001_initial')]

    operations = [
        migrations.AlterField(model_name='admission', name='parent_contact_number', field=models.CharField(max_length=30, null=True)),
        migrations.AlterField(model_name='admission', name='parent_whatsapp_number', field=models.CharField(max_length=30, null=True)),
        migrations.AlterField(model_name='historicaladmission', name='parent_contact_number', field=models.CharField(max_length=30, null=True)),
        migrations.AlterField(model_name='historicaladmission', name='parent_whatsapp_number', field=models.CharField(max_length=30, null=True)),
    ]
