# Generated by Django 4.2.7 on 2025-04-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('admission', '0002_admission_city_admission_district_admission_pin_code_and_more')]

    operations = [
        migrations.RenameField(model_name='admission', old_name='communication_address', new_name='home_address'),
        migrations.RenameField(model_name='historicaladmission', old_name='communication_address', new_name='home_address'),
        migrations.RemoveField(model_name='admission', name='permanent_address'),
        migrations.RemoveField(model_name='historicaladmission', name='permanent_address'),
    ]
