# Generated by Django 4.2.7 on 2025-05-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0002_initial')]

    operations = [
        migrations.AlterField(model_name='admission', name='joining_date', field=models.DateField(null=True)),
        migrations.AlterField(model_name='historicaladmission', name='joining_date', field=models.DateField(null=True)),
    ]
