# Generated by Django 4.2.7 on 2025-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0002_initial')]

    operations = [
        migrations.AlterField(model_name='feereceipt', name='date', field=models.DateTimeField(null=True)),
        migrations.AlterField(model_name='historicalfeereceipt', name='date', field=models.DateTimeField(null=True)),
    ]
