# Generated by Django 4.2.7 on 2025-05-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('masters', '0001_initial'), ('admission', '0003_alter_admission_joining_date_and_more')]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='batch',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.batch'),
        )
    ]
