# Generated by Django 4.2.7 on 2025-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0003_rename_communication_address_admission_home_address_and_more')]

    operations = [
        migrations.AddField(model_name='admission', name='document', field=models.FileField(blank=True, null=True, upload_to='admission/documents/')),
        migrations.AddField(model_name='historicaladmission', name='document', field=models.TextField(blank=True, max_length=100, null=True)),
    ]
