# Generated by Django 4.2.7 on 2025-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0004_admission_document_historicaladmission_document')]

    operations = [
        migrations.AddField(model_name='admission', name='signature', field=models.FileField(blank=True, null=True, upload_to='admission/signature/')),
        migrations.AddField(model_name='historicaladmission', name='signature', field=models.TextField(blank=True, max_length=100, null=True)),
    ]
