# Generated by Django 4.2.7 on 2025-05-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('employees', '0002_employee_is_also_telecaller_and_more'), ('admission', '0004_alter_admission_batch')]

    operations = [
        migrations.AlterModelOptions(name='admissionenquiry', options={'ordering': ['-id'], 'verbose_name': 'Admission Enquiry', 'verbose_name_plural': 'Admission Enquiries'}),
        migrations.AlterModelOptions(
            name='historicaladmissionenquiry',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Admission Enquiry',
                'verbose_name_plural': 'historical Admission Enquiries',
            },
        ),
        migrations.AlterField(
            model_name='admissionenquiry', name='tele_caller', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')
        ),
        migrations.AlterField(
            model_name='historicaladmissionenquiry',
            name='tele_caller',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee'),
        ),
    ]
