# Generated by Django 4.2.7 on 2025-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0005_admission_signature_historicaladmission_signature')]

    operations = [
        migrations.AlterField(model_name='admission', name='admission_number', field=models.CharField(blank=True, max_length=10, null=True)),
        migrations.AlterField(model_name='historicaladmission', name='admission_number', field=models.CharField(blank=True, max_length=10, null=True)),
    ]
