# Generated by Django 4.2.7 on 2025-05-14 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0005_alter_admissionenquiry_options_and_more')]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='parent_contact_number',
            field=models.CharField(
                help_text='Enter Contact number with country code, e.g. 91987654321',
                max_length=12,
                null=True,
                validators=[django.core.validators.RegexValidator(message='Enter number in international format like 91987654321 (no + or spaces).', regex='^91\\d{10}$')],
            ),
        ),
        migrations.AlterField(
            model_name='admission',
            name='parent_whatsapp_number',
            field=models.CharField(
                help_text='Enter WhatsApp number with country code, e.g. 91987654321',
                max_length=12,
                null=True,
                validators=[django.core.validators.RegexValidator(message='Enter number in international format like 91987654321 (no + or spaces).', regex='^91\\d{10}$')],
            ),
        ),
        migrations.AlterField(
            model_name='historicaladmission',
            name='parent_contact_number',
            field=models.CharField(
                help_text='Enter Contact number with country code, e.g. 91987654321',
                max_length=12,
                null=True,
                validators=[django.core.validators.RegexValidator(message='Enter number in international format like 91987654321 (no + or spaces).', regex='^91\\d{10}$')],
            ),
        ),
        migrations.AlterField(
            model_name='historicaladmission',
            name='parent_whatsapp_number',
            field=models.CharField(
                help_text='Enter WhatsApp number with country code, e.g. 91987654321',
                max_length=12,
                null=True,
                validators=[django.core.validators.RegexValidator(message='Enter number in international format like 91987654321 (no + or spaces).', regex='^91\\d{10}$')],
            ),
        ),
    ]
