# Generated by Django 4.2.7 on 2025-05-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0006_alter_admission_parent_contact_number_and_more')]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceregister', options={'ordering': ['-date'], 'verbose_name': 'Batch Attendance Register', 'verbose_name_plural': 'Batch Attendance Registers'}
        ),
        migrations.AddField(model_name='attendance', name='login_time', field=models.TimeField(null=True)),
        migrations.AddField(model_name='attendance', name='logout_time', field=models.TimeField(null=True)),
        migrations.AddField(model_name='historicalattendance', name='login_time', field=models.TimeField(null=True)),
        migrations.AddField(model_name='historicalattendance', name='logout_time', field=models.TimeField(null=True)),
        migrations.AlterField(
            model_name='attendance', name='status', field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=30)
        ),
        migrations.AlterField(
            model_name='historicalattendance', name='status', field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=30)
        ),
    ]
