# Generated by Django 4.2.7 on 2025-05-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('admission', '0007_alter_attendanceregister_options_and_more')]

    operations = [migrations.RemoveField(model_name='admission', name='academic_year'), migrations.RemoveField(model_name='historicaladmission', name='academic_year')]
