# Generated by Django 4.2.7 on 2025-05-28 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('admission', '0008_remove_admission_academic_year_and_more')]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='enquiry_type',
            field=models.CharField(
                choices=[('public', 'Public Lead'), ('meta', 'Meta Lead'), ('campaign', 'Campaign Lead'), ('event', 'Event Lead'), ('referral', 'Referral Lead')],
                default=django.utils.timezone.now,
                max_length=80,
            ),
            preserve_default=False,
        ),
        migrations.AddField(model_name='admissionenquiry', name='next_enquiry_date', field=models.DateField(null=True)),
        migrations.AddField(model_name='admissionenquiry', name='remark', field=models.TextField(blank=True, null=True)),
        migrations.AddField(
            model_name='historicaladmissionenquiry',
            name='enquiry_type',
            field=models.CharField(
                choices=[('public', 'Public Lead'), ('meta', 'Meta Lead'), ('campaign', 'Campaign Lead'), ('event', 'Event Lead'), ('referral', 'Referral Lead')],
                default=django.utils.timezone.now,
                max_length=80,
            ),
            preserve_default=False,
        ),
        migrations.AddField(model_name='historicaladmissionenquiry', name='next_enquiry_date', field=models.DateField(null=True)),
        migrations.AddField(model_name='historicaladmissionenquiry', name='remark', field=models.TextField(blank=True, null=True)),
    ]
