# Generated by Django 4.2.7 on 2025-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0009_admissionenquiry_enquiry_type_and_more')]

    operations = [
        migrations.AlterField(
            model_name='admissionenquiry',
            name='enquiry_type',
            field=models.CharField(
                choices=[
                    ('public_lead', 'Public Lead'),
                    ('meta_lead', 'Meta Lead'),
                    ('campaign_lead', 'Campaign Lead'),
                    ('event_lead', 'Event Lead'),
                    ('referral_lead', 'Referral Lead'),
                ],
                default='public_lead',
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name='historicaladmissionenquiry',
            name='enquiry_type',
            field=models.CharField(
                choices=[
                    ('public_lead', 'Public Lead'),
                    ('meta_lead', 'Meta Lead'),
                    ('campaign_lead', 'Campaign Lead'),
                    ('event_lead', 'Event Lead'),
                    ('referral_lead', 'Referral Lead'),
                ],
                default='public_lead',
                max_length=80,
            ),
        ),
    ]
