# Generated by Django 4.2 on 2025-06-03 10:35

import admission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('masters', '0004_remove_batch_academic_year_and_more'), ('branches', '0001_initial'), ('admission', '0010_alter_admissionenquiry_enquiry_type_and_more')]

    operations = [
        migrations.RemoveField(model_name='admissionenquiry', name='date_of_birth'),
        migrations.RemoveField(model_name='admissionenquiry', name='parent_contact_number'),
        migrations.RemoveField(model_name='admissionenquiry', name='parent_full_name'),
        migrations.RemoveField(model_name='admissionenquiry', name='parent_mail_id'),
        migrations.RemoveField(model_name='admissionenquiry', name='parent_whatsapp_number'),
        migrations.RemoveField(model_name='admissionenquiry', name='personal_email'),
        migrations.RemoveField(model_name='admissionenquiry', name='pin_code'),
        migrations.RemoveField(model_name='admissionenquiry', name='religion'),
        migrations.RemoveField(model_name='admissionenquiry', name='whatsapp_number'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='date_of_birth'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='parent_contact_number'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='parent_full_name'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='parent_mail_id'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='parent_whatsapp_number'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='personal_email'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='pin_code'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='religion'),
        migrations.RemoveField(model_name='historicaladmissionenquiry', name='whatsapp_number'),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to=admission.models.active_objects, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AlterField(model_name='admissionenquiry', name='contact_number', field=models.CharField(max_length=100, null=True)),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='course',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.course'),
        ),
        migrations.AlterField(model_name='admissionenquiry', name='next_enquiry_date', field=models.DateField(blank=True, null=True)),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='status',
            field=models.CharField(
                choices=[
                    ('new_enquiry', 'New Enquiry'),
                    ('no_response', 'No Response'),
                    ('follow_up', 'Follow Up'),
                    ('demo', 'Ready for Demo'),
                    ('interested', 'Interested'),
                    ('admitted', 'Admitted'),
                    ('rejected', 'Rejected'),
                ],
                default='new_enquiry',
                max_length=30,
            ),
        ),
        migrations.AlterField(model_name='historicaladmissionenquiry', name='contact_number', field=models.CharField(max_length=100, null=True)),
        migrations.AlterField(model_name='historicaladmissionenquiry', name='next_enquiry_date', field=models.DateField(blank=True, null=True)),
        migrations.AlterField(
            model_name='historicaladmissionenquiry',
            name='status',
            field=models.CharField(
                choices=[
                    ('new_enquiry', 'New Enquiry'),
                    ('no_response', 'No Response'),
                    ('follow_up', 'Follow Up'),
                    ('demo', 'Ready for Demo'),
                    ('interested', 'Interested'),
                    ('admitted', 'Admitted'),
                    ('rejected', 'Rejected'),
                ],
                default='new_enquiry',
                max_length=30,
            ),
        ),
    ]
