# Generated by Django 4.2 on 2025-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0011_remove_admissionenquiry_date_of_birth_and_more')]

    operations = [
        migrations.AlterModelOptions(name='admissionenquiry', options={'ordering': ['id'], 'verbose_name': 'Admission Enquiry', 'verbose_name_plural': 'Admission Enquiries'}),
        migrations.AlterField(model_name='feereceipt', name='date', field=models.DateField(null=True)),
        migrations.AlterField(model_name='historicalfeereceipt', name='date', field=models.DateField(null=True)),
    ]
