# Generated by Django 4.2 on 2025-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('admission', '0012_alter_admissionenquiry_options_alter_feereceipt_date_and_more')]

    operations = [
        migrations.AlterField(model_name='feereceipt', name='receipt_no', field=models.CharField(max_length=10, null=True)),
        migrations.AlterField(model_name='historicalfeereceipt', name='receipt_no', field=models.CharField(max_length=10, null=True)),
    ]
