# Generated by Django 4.2.7 on 2025-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0001_initial')]

    operations = [
        migrations.AddField(model_name='employee', name='is_also_telecaller', field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=128)),
        migrations.AddField(
            model_name='historicalemployee', name='is_also_telecaller', field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=128)
        ),
    ]
