# Generated by Django 4.2.7 on 2025-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0002_employee_is_also_telecaller_and_more')]

    operations = [
        migrations.RenameField(model_name='employee', old_name='is_also_telecaller', new_name='is_also_tele_caller'),
        migrations.RemoveField(model_name='historicalemployee', name='is_also_telecaller'),
        migrations.AddField(
            model_name='historicalemployee', name='is_also_tele_caller', field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=128)
        ),
    ]
