# Generated by Django 4.2.7 on 2025-05-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('branches', '0001_initial'), ('employees', '0003_rename_is_also_telecaller_employee_is_also_tele_caller_and_more')]

    operations = [
        migrations.AlterField(model_name='employee', name='branch', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'))
    ]
