# Generated by Django 4.2.7 on 2025-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='historicalsetting', name='branch'),
        migrations.RemoveField(model_name='historicalsetting', name='document_settings'),
        migrations.RemoveField(model_name='setting', name='branch'),
        migrations.RemoveField(model_name='setting', name='document_settings'),
        migrations.AddField(model_name='historicalsetting', name='access_token', field=models.CharField(max_length=50, null=True)),
        migrations.AddField(model_name='historicalsetting', name='instance_id', field=models.CharField(max_length=50, null=True)),
        migrations.AddField(model_name='setting', name='access_token', field=models.CharField(max_length=50, null=True)),
        migrations.AddField(model_name='setting', name='instance_id', field=models.CharField(max_length=50, null=True)),
    ]
