# Generated by Django 4.2.7 on 2025-05-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_remove_admission_academic_year_and_more'),
        ('masters', '0004_remove_batch_academic_year_and_more'),
        ('core', '0002_remove_historicalsetting_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='historicalacademicyear', name='creator'),
        migrations.RemoveField(model_name='historicalacademicyear', name='history_user'),
        migrations.DeleteModel(name='AcademicYear'),
        migrations.DeleteModel(name='HistoricalAcademicYear'),
    ]
