# Generated by Django 4.2.7 on 2025-05-02 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='attachment',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='chat_attachments/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])],
            ),
        ),
        migrations.AddField(
            model_name='historicalchatsession',
            name='attachment',
            field=models.TextField(
                blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])]
            ),
        ),
    ]
