# Generated by Django 4.2.7 on 2025-05-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0001_initial')]

    operations = [
        migrations.AddField(model_name='batch', name='ending_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='batch', name='starting_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='historicalbatch', name='ending_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='historicalbatch', name='starting_date', field=models.DateField(blank=True, null=True)),
    ]
