# Generated by Django 4.2.7 on 2025-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0002_chatsession_attachment_and_more')]

    operations = [
        migrations.AddField(model_name='chatsession', name='read', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='historicalchatsession', name='read', field=models.BooleanField(default=False)),
    ]
