# Generated by Django 4.2.7 on 2025-05-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('masters', '0003_chatsession_read_historicalchatsession_read')]

    operations = [migrations.RemoveField(model_name='batch', name='academic_year'), migrations.RemoveField(model_name='historicalbatch', name='academic_year')]
