# Generated by Django 4.2.7 on 2025-04-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('branches', '0001_initial'), ('masters', '0003_historicalcomplaintregistration_and_more')]

    operations = [
        migrations.AddField(
            model_name='complaintregistration', name='branch', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')
        ),
        migrations.AddField(
            model_name='complaintregistration',
            name='status',
            field=models.CharField(
                choices=[('Complaint Registered', 'Complaint Registered'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')],
                default='Complaint Registered',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplaintregistration',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='historicalcomplaintregistration',
            name='status',
            field=models.CharField(
                choices=[('Complaint Registered', 'Complaint Registered'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')],
                default='Complaint Registered',
                max_length=30,
            ),
        ),
    ]
