# Generated by Django 4.2.7 on 2025-05-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('masters', '0003_alter_batch_ending_date_alter_batch_starting_date_and_more')]

    operations = [migrations.RemoveField(model_name='batch', name='academic_year'), migrations.RemoveField(model_name='historicalbatch', name='academic_year')]
