# Generated by Django 4.2.7 on 2025-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0005_remove_historicalsyllabus_description_and_more')]

    operations = [
        migrations.AlterField(model_name='historicalsyllabusitem', name='status', field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default='False', max_length=10)),
        migrations.AlterField(model_name='syllabusitem', name='status', field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default='False', max_length=10)),
    ]
