# Generated by Django 4.2.7 on 2025-05-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0006_placementrequest_historicalplacementrequest')]

    operations = [
        migrations.AddField(
            model_name='historicalplacementrequest',
            name='status',
            field=models.CharField(
                choices=[('Request Send', 'Request Send'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=30
            ),
        ),
        migrations.AddField(
            model_name='placementrequest',
            name='status',
            field=models.CharField(
                choices=[('Request Send', 'Request Send'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=30
            ),
        ),
    ]
