# Generated by Django 4.2.7 on 2025-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0006_alter_historicalsyllabusitem_status_and_more')]

    operations = [
        migrations.AlterField(
            model_name='historicalsyllabusitem', name='status', field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=10)
        ),
        migrations.AlterField(
            model_name='syllabusitem', name='status', field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=10)
        ),
    ]
