# Generated by Django 4.2.7 on 2025-04-30 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_alter_admission_admission_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('masters', '0007_alter_historicalsyllabusitem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSyllabusStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.batch')),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(app_label)s_%(class)s_creator',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('student', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='admission.admission')),
            ],
            options={'ordering': ['-created'], 'abstract': False},
        ),
        migrations.CreateModel(
            name='HistoricalBatchSyllabusStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.batch')),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
                    ),
                ),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                (
                    'student',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={'is_active': True},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='admission.admission',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical batch syllabus status',
                'verbose_name_plural': 'historical batch syllabus statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(model_name='syllabusitem', name='creator'),
        migrations.RemoveField(model_name='syllabusitem', name='syllabus'),
        migrations.AlterModelOptions(
            name='historicalsyllabus',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Syllabus',
                'verbose_name_plural': 'historical Syllabuses',
            },
        ),
        migrations.AlterModelOptions(name='syllabus', options={'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabuses'}),
        migrations.RemoveField(model_name='historicalsyllabus', name='batch'),
        migrations.RemoveField(model_name='syllabus', name='batch'),
        migrations.AddField(model_name='historicalsyllabus', name='description', field=models.TextField(blank=True, null=True)),
        migrations.AddField(model_name='historicalsyllabus', name='title', field=models.CharField(default=1, max_length=120), preserve_default=False),
        migrations.AddField(model_name='historicalsyllabus', name='week', field=models.CharField(default=1, max_length=120), preserve_default=False),
        migrations.AddField(model_name='syllabus', name='description', field=models.TextField(blank=True, null=True)),
        migrations.AddField(model_name='syllabus', name='title', field=models.CharField(default=1, max_length=120), preserve_default=False),
        migrations.AddField(model_name='syllabus', name='week', field=models.CharField(default=1, max_length=120), preserve_default=False),
        migrations.DeleteModel(name='HistoricalSyllabusItem'),
        migrations.DeleteModel(name='SyllabusItem'),
        migrations.AddField(
            model_name='historicalbatchsyllabusstatus',
            name='syllabus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.syllabus'),
        ),
        migrations.AddField(
            model_name='historicalbatchsyllabusstatus',
            name='teacher',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'user__usertype': 'teacher'},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='employees.employee',
            ),
        ),
        migrations.AddField(model_name='batchsyllabusstatus', name='syllabus', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.syllabus')),
        migrations.AddField(
            model_name='batchsyllabusstatus',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user__usertype': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
