# Generated by Django 4.2.7 on 2025-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0007_historicalplacementrequest_status_and_more')]

    operations = [
        migrations.AlterField(
            model_name='historicalplacementrequest',
            name='status',
            field=models.CharField(
                choices=[('Request Send', 'Request Send'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected')],
                default='Request Send',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='placementrequest',
            name='status',
            field=models.CharField(
                choices=[('Request Send', 'Request Send'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected')],
                default='Request Send',
                max_length=30,
            ),
        ),
    ]
