# Generated by Django 4.2.7 on 2025-04-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('masters', '0008_batchsyllabusstatus_historicalbatchsyllabusstatus_and_more')]

    operations = [
        migrations.AddField(model_name='batch', name='course', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.course')),
        migrations.AddField(
            model_name='historicalbatch',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.course'),
        ),
    ]
