# Generated by Django 4.2.7 on 2025-05-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0008_alter_historicalplacementrequest_status_and_more')]

    operations = [
        migrations.AlterField(
            model_name='historicalplacementrequest', name='resume', field=models.URLField(help_text='Please provide a link to your resume.', verbose_name='Resume Link')
        ),
        migrations.AlterField(model_name='placementrequest', name='resume', field=models.URLField(help_text='Please provide a link to your resume.', verbose_name='Resume Link')),
    ]
