# Generated by Django 4.2.7 on 2025-04-30 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('masters', '0009_batch_course_historicalbatch_course')]

    operations = [
        migrations.RemoveField(model_name='batchsyllabusstatus', name='student'),
        migrations.RemoveField(model_name='batchsyllabusstatus', name='teacher'),
        migrations.RemoveField(model_name='historicalbatchsyllabusstatus', name='student'),
        migrations.RemoveField(model_name='historicalbatchsyllabusstatus', name='teacher'),
        migrations.AddField(
            model_name='batchsyllabusstatus', name='status', field=models.CharField(choices=[('pending', 'pending'), ('completed', 'Completed')], default='pending', max_length=50)
        ),
        migrations.AddField(
            model_name='batchsyllabusstatus',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbatchsyllabusstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalbatchsyllabusstatus',
            name='user',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
