# Generated by Django 4.2.7 on 2025-05-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('admission', '0001_initial'), ('masters', '0009_alter_historicalplacementrequest_resume_and_more')]

    operations = [
        migrations.AddField(
            model_name='historicalplacementrequest',
            name='portfolio_link',
            field=models.URLField(blank=True, help_text='Link to your portfolio or work samples', verbose_name='Portfolio Link'),
        ),
        migrations.AddField(
            model_name='placementrequest',
            name='portfolio_link',
            field=models.URLField(blank=True, help_text='Link to your portfolio or work samples', verbose_name='Portfolio Link'),
        ),
        migrations.AlterField(
            model_name='placementrequest', name='student', field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission')
        ),
    ]
