# Generated by Django 4.2.7 on 2025-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0010_historicalplacementrequest_portfolio_link_and_more')]

    operations = [
        migrations.RemoveField(model_name='historicalplacementrequest', name='about_you'),
        migrations.RemoveField(model_name='historicalplacementrequest', name='career_goals'),
        migrations.RemoveField(model_name='historicalplacementrequest', name='self_intro'),
        migrations.RemoveField(model_name='placementrequest', name='about_you'),
        migrations.RemoveField(model_name='placementrequest', name='career_goals'),
        migrations.RemoveField(model_name='placementrequest', name='self_intro'),
        migrations.AddField(
            model_name='historicalplacementrequest',
            name='behance_link',
            field=models.URLField(blank=True, help_text='Link to your Behance portfolio', verbose_name='Behance Profile Link'),
        ),
        migrations.AddField(
            model_name='historicalplacementrequest',
            name='experience',
            field=models.TextField(blank=True, help_text='Please provide details of your experience, if any.', verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='placementrequest', name='behance_link', field=models.URLField(blank=True, help_text='Link to your Behance portfolio', verbose_name='Behance Profile Link')
        ),
        migrations.AddField(
            model_name='placementrequest',
            name='experience',
            field=models.TextField(blank=True, help_text='Please provide details of your experience, if any.', verbose_name='Experience'),
        ),
    ]
