# Generated by Django 4.2.7 on 2025-04-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('masters', '0010_remove_batchsyllabusstatus_student_and_more')]

    operations = [
        migrations.AddField(model_name='historicalsyllabus', name='is_completed', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='syllabus', name='is_completed', field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name='batchsyllabusstatus', name='status', field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)
        ),
        migrations.AlterField(
            model_name='historicalbatchsyllabusstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
