# Generated by Django 4.2.7 on 2025-05-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial'), ('masters', '0011_remove_historicalplacementrequest_about_you_and_more')]

    operations = [
        migrations.AddField(model_name='batch', name='academic_year', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
        migrations.AddField(
            model_name='historicalbatch',
            name='academic_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.academicyear'),
        ),
    ]
