# Generated by Django 4.2.7 on 2025-05-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('accounts', '0003_alter_user_usertype')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(
                choices=[
                    ('admin_staff', 'Admin Staff'),
                    ('branch_staff', 'Branch Staff'),
                    ('teacher', 'Teacher'),
                    ('mentor', 'Mentor'),
                    ('sales_head', 'Sales Head'),
                    ('tele_caller', 'Tele Caller'),
                    ('student', 'Student'),
                ],
                max_length=30,
                verbose_name='Permissions',
            ),
        )
    ]
