# Generated by Django 4.2.7 on 2025-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('branches', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='branch', name='address'),
        migrations.RemoveField(model_name='historicalbranch', name='address'),
        migrations.AddField(model_name='branch', name='district', field=models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField(model_name='historicalbranch', name='district', field=models.CharField(blank=True, max_length=100, null=True)),
    ]
