# Generated by Django 4.2.7 on 2025-04-03 08:20

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance_type', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Cr', 'Cr')], max_length=5, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('alias_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.PositiveBigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_no_off', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone No. (Off)')),
                ('phone_no_res', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone No. (Res)')),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=128, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={'ordering': ['-created'], 'abstract': False},
        ),
        migrations.CreateModel(
            name='GroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                (
                    'nature_of_group',
                    models.CharField(
                        choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=30
                    ),
                ),
                (
                    'main_group',
                    models.CharField(
                        choices=[('balance_sheet', 'Balance Sheet'), ('profit_and_loss', 'Profit & Loss'), ('cash_flow', 'Cash Flow Statement'), ('others', 'Others')],
                        max_length=30,
                    ),
                ),
                ('is_locked', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={'ordering': ['-created'], 'abstract': False},
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance_type', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Cr', 'Cr')], max_length=5, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('alias_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.PositiveBigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_no_off', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone No. (Off)')),
                ('phone_no_res', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone No. (Res)')),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=128, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGroupMaster',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                (
                    'nature_of_group',
                    models.CharField(
                        choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=30
                    ),
                ),
                (
                    'main_group',
                    models.CharField(
                        choices=[('balance_sheet', 'Balance Sheet'), ('profit_and_loss', 'Profit & Loss'), ('cash_flow', 'Cash Flow Statement'), ('others', 'Others')],
                        max_length=30,
                    ),
                ),
                ('is_locked', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical group master',
                'verbose_name_plural': 'historical group masters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
